version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
  deploy:  # Add a post_build phase for deployment
    commands:
      - echo "Deployment phase started"
      - cdk deploy --require-approval never  
artifacts:
  files:
    - '**/*'
