version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
  post_build:  # Add a post_build phase for deployment
    commands:
      - echo "Deployment phase started"
      # Optional: Add deployment-specific commands here
      - cdk deploy --require-approval never  # Re-run deploy if needed for additional actions (or use other deployment methods)
artifacts:
  files:
    - '**/*'
